import subprocess
import json
import os
import sys

def run_command(cmd):
    print(f"\n>>> RUNNING: {cmd}")
    result = subprocess.run(cmd, shell=True)
    if result.returncode != 0:
        print(f"Error running command: {cmd}")
        sys.exit(result.returncode)

def main():
    print("=== Starting Gesture Recognition Pipeline ===")
    
    # 1. Read Config to determine final filename for train.py
    with open("pipeline_config.json", "r") as f:
        config = json.load(f)

    pool_lbl = "pool" if config["use_pooling"] else "raw"
    rm_dup_lbl = "simple" if config["remove_duplicates"] else "complex"
    
    # Construct folder/file name
    subdir_name = (
        f"{pool_lbl}_iou{config['iou_threshold']:.2f}_"
        f"move{config['movement_threshold']:.2f}_"
        f"dist{config['max_match_dist']:.0f}_{rm_dup_lbl}"
    )
    
    # The file generated by merge_col.py
    final_train_file = f"{config['feature_dir']}/{subdir_name}_features_extended_rewritten.csv"

    # 2. Execute Pipeline Steps
    
    # Step A: Build Networks (R)
    run_command("Rscript build_network.R")
    
    # Step B: Extract Features (R)
    run_command("Rscript extract_features.R")
    
    # Step C: Merge & Clean (Python)
    run_command("python merge_col.py")
    
    # Step D: Train Model (Python)
    # Pass the dynamically determined file path
    run_command(f"python train.py {final_train_file}")

    print("\n=== Pipeline Completed Successfully ===")

if __name__ == "__main__":
    main()